### ISSUE TITLE
Add django 1.8 compatibility

### ISSUE THREAD

**Issue by melinath** [alex/django-filter#226]
I'm currently getting the following exception after upgrading to 1.8:

```
AttributeError: 'ManyToOneRel' object has no attribute 'opts'
```

I don't know how many other incompatibilities there are.

**Comment by kevin-brown** [comment]
Both https://github.com/alex/django-filter/pull/224 and https://github.com/alex/django-filter/pull/225 were opened to fix this. I think that's the only place left that needs to be fixed, the rest were handled in https://github.com/alex/django-filter/issues/209.

**Comment by melinath** [comment]
Apologies for the duplicate.
